[packages.solux]
versioned_files = ["packages/core/package.json"]
changelog = "packages/core/CHANGELOG.md"
assets = "packages/core/artifacts/*"
scopes = ["core", "general"]

[github]
owner = "carere"
repo = "solux"
