name: Continuous Integration on release branches

on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node & pnpm
        uses: carere/setup-node-and-pnpm@v1.2
        with:
          node-version: 20
          pnpm-version: 8

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build
        
      - name: Release new package version
        run: pnpm semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
